server:
    port: 8500
spring:
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;
        driverClassName: com.mysql.cj.jdbc.Driver
        filters: config,stat,wall
        initialSize: 5
        logSlowSql: true
        maxActive: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: false
        publicKey: ''
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://172.168.3.31:3306/noumena_2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: noumena
        password: Noumena@2020
        validationQuery: SELECT 1 FROM DUAL
    redis:
      database: 0
      host: localhost
      password: ""
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
        port: 6379
        timeout: 10000
